version: "3.8"

services:
  frontend:
    image: shimulmahmud/dashboard-client # Replace with your frontend image
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app_network

  backend:
    image: shimulmahmud/dashboard-server # Replace with your backend image
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo
    networks:
      - app_network

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

volumes:
  mongo_data:

networks:
  app_network:
